version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\Nodinite.Serilog.Sink.Core\Nodinite.Serilog.Sink.Core\bin\Debug\'
   name: Sink
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core.Tests/Nodinite.Serilog.Sink.Core.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off