version: '1.0.{build}'
image: Visual Studio 2017
configuration:
  - Release
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core/Nodinite.Serilog.Sink.Core.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\Nodinite.Serilog.Sink.Core\Nodinite.Serilog.Sink.Core\bin\Release\'
   name: Sink
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off